CREATE TABLE departments (
id INTEGER PRIMARY KEY
name VARCHAR(50) NOT NULL
);

CREATE TABLE roles (
id INTEGER PRIMARY KEY
title VARCHAR(50) NOT NULL
salary INTEGER NOT NULL
);

CREATE TABLE employees (
id INTEGER PRIMARY KEY
first_name VARCHAR(30) NOT NULL
last_name VARCHAR(30) NOT NULL
job_title VARCHAR(50) NOT NULL
department VARCHAR(50) NOT NULL
salary INTEGER NOT NULL
manager VARCHAR(50) NOT NULL
);